### ISSUE TITLE
E_reputation not working

### ISSUE THREAD

**Issue by nans64** [amadeus4dev/amadeus-ruby#39]
## Description

I've been trying to use e_reputation but it's not working

## Steps to Reproduce

1. amadeus.e_reputation.hotel_sentiments.get(hotelIds: 'SJNYCAJA,TELONMFS')
2. Result -> NoMethodError (undefined method `e_reputation' for #<Amadeus::Client:0x000055adba09e850>)

__Expected Behavior: e_reputation is a method

__Actual Behavior:__ e_reputation not a method

__Stable Behavior?__ 100%

## Versions

[What version of Ruby/Rubygems are you running? What Operating System are you on?]
Ruby 5.2

## Checklist

Please make sure you checked the following:

* Are you running Ruby 2.2+? Yes
* Did you download the latest version of this gem? Yes

**Comment by anthonyroux** [comment]
New version 3.3.0 released fixing the issue.
